### ISSUE TITLE
嘗試使用NER時出現assertion error

### ISSUE THREAD

**Issue by hyusterr** [ckiplab/ckiptagger#18]
按照 README 建置 pipeline 時，出現以下錯誤，請問應該如何解決
```---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-37-0e6a5bf68427> in <module>
----> 1 ner_list = ner( sent_list, pos_list )

D:\python3.7\lib\site-packages\ckiptagger\api.py in __call__(self, word_sentence_list, pos_sentence_list, character_normalization, batch_sentences, batch_characters)
    306                 word_sentence = [unicodedata.normalize("NFKD", raw_word) for raw_word in raw_word_sentence]
    307                 sentence, normal_to_raw_index = _normalize_sentence("".join(raw_word_sentence))
--> 308                 assert sentence == "".join(word_sentence)
    309                 word_sentence_list.append(word_sentence)
    310                 normal2raw_list.append(normal_to_raw_index)

AssertionError:

**Comment by hyusterr** [comment]
看來是因為 POS 的輸入放的不是 WS 的輸出的問題，手殘，沒事了

**Comment by hyusterr** [comment]
重新嘗試之後仍有問題：
```
Traceback (most recent call last):
  File ".\db2019-final.py", line 41, in <module>
    ner_list = ner(sent_list[40000:50000], pos_list[40000:50000])
  File "D:\python3.7\lib\site-packages\ckiptagger\api.py", line 308, in __call__
    assert sentence == "".join(word_sentence)
AssertionError
```
想請問造成這樣問題的原因是？

**Comment by hyusterr** [comment]
看起來應該是句子裡有顏文字，編碼沒有處理好的問題
