### ISSUE TITLE
'WS' object has no attribute 'model'

### ISSUE THREAD

**Issue by freezexpert** [ckiplab/ckiptagger#45]
如題，我在執行github上的demo.py時，總是會出現這個錯誤訊息，想知道有什麼解決辦法

**Comment by doggy8088** [comment]
我也遇到一樣的問題：

```txt
WARNING:tensorflow:From C:\Python312\Lib\site-packages\ckiptagger\api.py:8: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

Traceback (most recent call last):
  File "C:\Projects\CkipTaggerDemo\demo.py", line 9, in <module>
    ws = WS("./data")
         ^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\ckiptagger\api.py", line 52, in __init__      
    model = model_ws.Model(config)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\ckiptagger\model_ws.py", line 213, in __init__
    self.create_encoder()
  File "C:\Python312\Lib\site-packages\ckiptagger\model_ws.py", line 252, in create_encoder
    self.bilstm = Cross_BiLSTM(
                  ^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\ckiptagger\model_ws.py", line 98, in __init__
    self.create_cell(current_input_d, hidden_d, is_top_cell, f"lstm_cell_{layer+1}")
  File "C:\Python312\Lib\site-packages\ckiptagger\model_ws.py", line 106, in create_cell
    cell = tf.compat.v1.nn.rnn_cell.LSTMCell(hidden_d, name=name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tensorflow\python\util\lazy_loader.py", line 207, in __getattr__      
    raise AttributeError(
AttributeError: `LSTMCell` is not available with Keras 3.
Exception ignored in: <function WS.__del__ at 0x000001AE64306700>
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\ckiptagger\api.py", line 65, in __del__
    self.model.sess.close()
    ^^^^^^^^^^
AttributeError: 'WS' object has no attribute 'model'
```

**Comment by doggy8088** [comment]
我改安裝 Python 到 3.7 版就解決了，因為 TensorFlow 1.x 不支援 Python 3.8 以上版本。

若要成功執行，還要安裝比較舊版的 ` protobuf` 套件：

```sh
pip install protobuf=3.20
```

**Comment by wastu01** [comment]
我在 python 3.10, tensorflow 2.17.0 環境執行一樣遇到同樣問題
WS object has no attribute 'mode
不過我是使用 Mac 沒辦法裝 TensorFlow 1.x 版本要另外想辦法

**Comment by wastu01** [comment]
> 我改安裝 Python 到 3.7 版就解決了，因為 TensorFlow 1.x 不支援 Python 3.8 以上版本。
> 
> 若要成功執行，還要安裝比較舊版的 ` protobuf` 套件：
> 
> ```shell
> pip install protobuf=3.20
> ```
應該是
`pip install protobuf==3.20`

**Comment by jasonyen1009** [comment]
> 我在 python 3.10, tensorflow 2.17.0 環境執行一樣遇到同樣問題 WS object has no attribute 'mode 不過我是使用 Mac 沒辦法裝 TensorFlow 1.x 版本要另外想辦法

MacOS : 15.0.1
python : 3.8.20
tensorflow : 2.13.0

可以正常運行
